name: CD Pipeline

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Check what secrets are available
      run: |
        echo "=== Checking Secrets ==="
        echo "SSH_HOST exists: ${{ secrets.SSH_HOST != '' }}"
        echo "SSH_PORT exists: ${{ secrets.SSH_PORT != '' }}"
        echo "SSH_USERNAME exists: ${{ secrets.SSH_USERNAME != '' }}"
        echo "SSH_PRIVATE_KEY exists: ${{ secrets.SSH_PRIVATE_KEY != '' }}"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        rm -rf venv
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Execute remote SSH commands using SSH key
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "Starting deployment"

          echo "Inserting into project"
          cd /home/user/Desktop/lab1/catty-reminders-app 

          echo "Fetching"
          git fetch origin
          git reset --hard origin/github-actions

          echo "Dependencies"
          pip install -r requirements.txt

          echo "Start app"
          sudo systemctl restart app

          echo "Check: http://app.turmanidze.course.prafdin.ru
          
