name: CD Pipeline

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Check what secrets are available
      run: |
        echo "=== Checking Secrets ==="
        echo "SSH_HOST exists: ${{ secrets.SSH_HOST != '' }}"
        echo "SSH_PORT exists: ${{ secrets.SSH_PORT != '' }}"
        echo "SSH_USERNAME exists: ${{ secrets.SSH_USERNAME != '' }}"
        echo "SSH_PRIVATE_KEY exists: ${{ secrets.SSH_PRIVATE_KEY != '' }}"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy Docker container via ssh
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "Starting deployment"

          echo "Login ghcr"
          echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
 
          echo "Pulling"
          echo "${{ secrets.VM_PASS }}" | sudo -s docker pull ghcr.io/${{ github.repository }}/catty-reminders:docker

          echo "Delete old container"
          echo "${{ secrets.VM_PASS }}" | sudo -s docker stop catty-reminders || True
          echo "${{ secrets.VM_PASS }}" | sudo -so docker rm catty-reminders || True
          
          echo "Start app"
          echo "${{ secrets.VM_PASS }}" | sudo -s docker run -d \
            --name catty-reminders \
            -p 8181:8181 \
            --restart unless-stopped \
            ghcr.io/buddyuchiha/catty-reminders-app/catty-reminders:docker

          echo "Check: http://app.turmanidze.course.prafdin.ru"
          
